FROM python:3
ENV PYTHONUNBUFFERED 1
ARG ENV

# Create code source code folder
RUN mkdir /src


# Upgrade pip
RUN pip3 install --no-cache-dir --upgrade pip


# Install python packet
COPY requirements/${ENV}.txt /
RUN pip install -r ${ENV}.txt


# Copy source code to docker
ADD . /code
