version: "3.8"
services:
  django:
    build:
      context: ..
      args:
        ENV: ${ENV}
      dockerfile: docker/Dockerfile-fastapi
    command: bash -c "cd src &&
                      python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ../src:/src
    ports:
      - ${SERVER_PORT}:8000
    env_file:
      - ./.env
    restart: always
